name: GitHub-Profile-Summary-Cards

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.ACTION_TOKEN  }}, you can change to your personal access token
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN  }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 8
