name: GitHub-Profile-3D-Contrib

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - name: GetTime
        run: echo "DATE=$(TZ='Asia/Shanghai' date +%Y-%m-%d\ %H:%M\ %Z)" >> $GITHUB_ENV
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: 提交更改
        run: |
          git config --local user.email "qq2236639958@outlook.com"
          git config --local user.name "qq2236639958"
          git add .
          git commit -m "Update  OF ${{ env.DATE}}"
          git push -f
